# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use Ubuntu 14.04
  config.vm.box = "ubuntu/trusty64"

  # Forward the default HTTP port of the built in rails development server.
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

  # Set up rbenv and the specified ruby version.
  config.vm.provision "shell", path: "provision/setup.sh", privileged: false

  # Run this on every startup to deploy and start the app.
  config.vm.provision "shell", path: "provision/deploy.sh", privileged: false, run: "always"
end
